set_source_files_properties(qml/theme/Theme.qml PROPERTIES QT_QML_SINGLETON_TYPE TRUE)
set_source_files_properties(qml/state/ShellStore.qml PROPERTIES QT_QML_SINGLETON_TYPE TRUE)
set_source_files_properties(qml/desktop/components/DesktopTokens.qml PROPERTIES QT_QML_SINGLETON_TYPE TRUE)
set_source_files_properties(qml/components/InputPromptIcons.qml PROPERTIES QT_QML_SINGLETON_TYPE TRUE)
set_source_files_properties(qml/desktop/stream/overlay/OverlayStyle.qml PROPERTIES QT_QML_SINGLETON_TYPE TRUE)

set(OPENNOW_CONTROLLER_ICON_FILES
    res/input-prompts/controller_playstation5-dark.svg
    res/input-prompts/controller_playstation5.svg
    res/input-prompts/controller_xboxseries-dark.svg
    res/input-prompts/controller_xboxseries.svg
    res/input-prompts/xbox_button_a-dark.svg
    res/input-prompts/xbox_button_a.svg
    res/input-prompts/xbox_button_b-dark.svg
    res/input-prompts/xbox_button_b.svg
    res/input-prompts/xbox_button_menu-dark.svg
    res/input-prompts/xbox_button_menu.svg
    res/input-prompts/xbox_button_view-dark.svg
    res/input-prompts/xbox_button_view.svg
    res/input-prompts/xbox_button_x-dark.svg
    res/input-prompts/xbox_button_x.svg
    res/input-prompts/xbox_button_y-dark.svg
    res/input-prompts/xbox_button_y.svg
    res/input-prompts/xbox_guide-dark.svg
    res/input-prompts/xbox_guide.svg
    res/input-prompts/xbox_lb-dark.svg
    res/input-prompts/xbox_lb.svg
    res/input-prompts/xbox_lt-dark.svg
    res/input-prompts/xbox_lt.svg
    res/input-prompts/xbox_rb-dark.svg
    res/input-prompts/xbox_rb.svg
    res/input-prompts/xbox_rt-dark.svg
    res/input-prompts/xbox_rt.svg
)

set(OPENNOW_KEYBOARD_ICON_FILES
    res/input-prompts/keyboard-dark.svg
    res/input-prompts/keyboard.svg
    res/input-prompts/keyboard_0-dark.svg
    res/input-prompts/keyboard_0.svg
    res/input-prompts/keyboard_1-dark.svg
    res/input-prompts/keyboard_1.svg
    res/input-prompts/keyboard_2-dark.svg
    res/input-prompts/keyboard_2.svg
    res/input-prompts/keyboard_3-dark.svg
    res/input-prompts/keyboard_3.svg
    res/input-prompts/keyboard_4-dark.svg
    res/input-prompts/keyboard_4.svg
    res/input-prompts/keyboard_5-dark.svg
    res/input-prompts/keyboard_5.svg
    res/input-prompts/keyboard_6-dark.svg
    res/input-prompts/keyboard_6.svg
    res/input-prompts/keyboard_7-dark.svg
    res/input-prompts/keyboard_7.svg
    res/input-prompts/keyboard_8-dark.svg
    res/input-prompts/keyboard_8.svg
    res/input-prompts/keyboard_9-dark.svg
    res/input-prompts/keyboard_9.svg
    res/input-prompts/keyboard_a-dark.svg
    res/input-prompts/keyboard_a.svg
    res/input-prompts/keyboard_alt-dark.svg
    res/input-prompts/keyboard_alt.svg
    res/input-prompts/keyboard_apostrophe-dark.svg
    res/input-prompts/keyboard_apostrophe.svg
    res/input-prompts/keyboard_arrow_down-dark.svg
    res/input-prompts/keyboard_arrow_down.svg
    res/input-prompts/keyboard_arrow_left-dark.svg
    res/input-prompts/keyboard_arrow_left.svg
    res/input-prompts/keyboard_arrow_right-dark.svg
    res/input-prompts/keyboard_arrow_right.svg
    res/input-prompts/keyboard_arrow_up-dark.svg
    res/input-prompts/keyboard_arrow_up.svg
    res/input-prompts/keyboard_arrows-dark.svg
    res/input-prompts/keyboard_arrows.svg
    res/input-prompts/keyboard_arrows_vertical-dark.svg
    res/input-prompts/keyboard_arrows_vertical.svg
    res/input-prompts/keyboard_b-dark.svg
    res/input-prompts/keyboard_b.svg
    res/input-prompts/keyboard_backspace_icon-dark.svg
    res/input-prompts/keyboard_backspace_icon.svg
    res/input-prompts/keyboard_bracket_close-dark.svg
    res/input-prompts/keyboard_bracket_close.svg
    res/input-prompts/keyboard_bracket_open-dark.svg
    res/input-prompts/keyboard_bracket_open.svg
    res/input-prompts/keyboard_c-dark.svg
    res/input-prompts/keyboard_c.svg
    res/input-prompts/keyboard_comma-dark.svg
    res/input-prompts/keyboard_comma.svg
    res/input-prompts/keyboard_command-dark.svg
    res/input-prompts/keyboard_command.svg
    res/input-prompts/keyboard_ctrl-dark.svg
    res/input-prompts/keyboard_ctrl.svg
    res/input-prompts/keyboard_d-dark.svg
    res/input-prompts/keyboard_d.svg
    res/input-prompts/keyboard_delete-dark.svg
    res/input-prompts/keyboard_delete.svg
    res/input-prompts/keyboard_e-dark.svg
    res/input-prompts/keyboard_e.svg
    res/input-prompts/keyboard_end-dark.svg
    res/input-prompts/keyboard_end.svg
    res/input-prompts/keyboard_enter-dark.svg
    res/input-prompts/keyboard_enter.svg
    res/input-prompts/keyboard_equals-dark.svg
    res/input-prompts/keyboard_equals.svg
    res/input-prompts/keyboard_escape-dark.svg
    res/input-prompts/keyboard_escape.svg
    res/input-prompts/keyboard_f-dark.svg
    res/input-prompts/keyboard_f.svg
    res/input-prompts/keyboard_f1-dark.svg
    res/input-prompts/keyboard_f1.svg
    res/input-prompts/keyboard_f10-dark.svg
    res/input-prompts/keyboard_f10.svg
    res/input-prompts/keyboard_f11-dark.svg
    res/input-prompts/keyboard_f11.svg
    res/input-prompts/keyboard_f12-dark.svg
    res/input-prompts/keyboard_f12.svg
    res/input-prompts/keyboard_f2-dark.svg
    res/input-prompts/keyboard_f2.svg
    res/input-prompts/keyboard_f3-dark.svg
    res/input-prompts/keyboard_f3.svg
    res/input-prompts/keyboard_f4-dark.svg
    res/input-prompts/keyboard_f4.svg
    res/input-prompts/keyboard_f5-dark.svg
    res/input-prompts/keyboard_f5.svg
    res/input-prompts/keyboard_f6-dark.svg
    res/input-prompts/keyboard_f6.svg
    res/input-prompts/keyboard_f7-dark.svg
    res/input-prompts/keyboard_f7.svg
    res/input-prompts/keyboard_f8-dark.svg
    res/input-prompts/keyboard_f8.svg
    res/input-prompts/keyboard_f9-dark.svg
    res/input-prompts/keyboard_f9.svg
    res/input-prompts/keyboard_g-dark.svg
    res/input-prompts/keyboard_g.svg
    res/input-prompts/keyboard_h-dark.svg
    res/input-prompts/keyboard_h.svg
    res/input-prompts/keyboard_home-dark.svg
    res/input-prompts/keyboard_home.svg
    res/input-prompts/keyboard_i-dark.svg
    res/input-prompts/keyboard_i.svg
    res/input-prompts/keyboard_insert-dark.svg
    res/input-prompts/keyboard_insert.svg
    res/input-prompts/keyboard_j-dark.svg
    res/input-prompts/keyboard_j.svg
    res/input-prompts/keyboard_k-dark.svg
    res/input-prompts/keyboard_k.svg
    res/input-prompts/keyboard_l-dark.svg
    res/input-prompts/keyboard_l.svg
    res/input-prompts/keyboard_m-dark.svg
    res/input-prompts/keyboard_m.svg
    res/input-prompts/keyboard_minus-dark.svg
    res/input-prompts/keyboard_minus.svg
    res/input-prompts/keyboard_n-dark.svg
    res/input-prompts/keyboard_n.svg
    res/input-prompts/keyboard_o-dark.svg
    res/input-prompts/keyboard_o.svg
    res/input-prompts/keyboard_option-dark.svg
    res/input-prompts/keyboard_option.svg
    res/input-prompts/keyboard_p-dark.svg
    res/input-prompts/keyboard_p.svg
    res/input-prompts/keyboard_page_down-dark.svg
    res/input-prompts/keyboard_page_down.svg
    res/input-prompts/keyboard_page_up-dark.svg
    res/input-prompts/keyboard_page_up.svg
    res/input-prompts/keyboard_pause-dark.svg
    res/input-prompts/keyboard_pause.svg
    res/input-prompts/keyboard_period-dark.svg
    res/input-prompts/keyboard_period.svg
    res/input-prompts/keyboard_plus-dark.svg
    res/input-prompts/keyboard_plus.svg
    res/input-prompts/keyboard_printscreen-dark.svg
    res/input-prompts/keyboard_printscreen.svg
    res/input-prompts/keyboard_q-dark.svg
    res/input-prompts/keyboard_q.svg
    res/input-prompts/keyboard_question-dark.svg
    res/input-prompts/keyboard_question.svg
    res/input-prompts/keyboard_r-dark.svg
    res/input-prompts/keyboard_r.svg
    res/input-prompts/keyboard_return-dark.svg
    res/input-prompts/keyboard_return.svg
    res/input-prompts/keyboard_s-dark.svg
    res/input-prompts/keyboard_s.svg
    res/input-prompts/keyboard_semicolon-dark.svg
    res/input-prompts/keyboard_semicolon.svg
    res/input-prompts/keyboard_shift_icon-dark.svg
    res/input-prompts/keyboard_shift_icon.svg
    res/input-prompts/keyboard_slash_back-dark.svg
    res/input-prompts/keyboard_slash_back.svg
    res/input-prompts/keyboard_slash_forward-dark.svg
    res/input-prompts/keyboard_slash_forward.svg
    res/input-prompts/keyboard_space_icon-dark.svg
    res/input-prompts/keyboard_space_icon.svg
    res/input-prompts/keyboard_t-dark.svg
    res/input-prompts/keyboard_t.svg
    res/input-prompts/keyboard_tab_icon-dark.svg
    res/input-prompts/keyboard_tab_icon.svg
    res/input-prompts/keyboard_tilde-dark.svg
    res/input-prompts/keyboard_tilde.svg
    res/input-prompts/keyboard_u-dark.svg
    res/input-prompts/keyboard_u.svg
    res/input-prompts/keyboard_v-dark.svg
    res/input-prompts/keyboard_v.svg
    res/input-prompts/keyboard_w-dark.svg
    res/input-prompts/keyboard_w.svg
    res/input-prompts/keyboard_win-dark.svg
    res/input-prompts/keyboard_win.svg
    res/input-prompts/keyboard_x-dark.svg
    res/input-prompts/keyboard_x.svg
    res/input-prompts/keyboard_y-dark.svg
    res/input-prompts/keyboard_y.svg
    res/input-prompts/keyboard_z-dark.svg
    res/input-prompts/keyboard_z.svg
)

qt_add_qml_module(opennow-qt
    URI OpenNOW
    VERSION 1.0
    QML_FILES
        qml/Main.qml
        qml/components/AppChrome.qml
        qml/components/UpdateFailureDialog.qml
        qml/components/ShellViewport.qml
        qml/components/ArtworkSource.qml
        qml/components/ControllerGlyph.qml
        qml/components/InputPromptIcons.qml
        qml/components/KeyboardGlyph.qml
        qml/components/FilterDropdown.qml
        qml/components/FocusFrame.qml
        qml/components/GameTile.qml
        qml/components/GlassButton.qml
        qml/components/GlassPanel.qml
        qml/components/HintBar.qml
        qml/components/HomeTileMenu.qml
        qml/components/MotionProgress.qml
        qml/components/NavPill.qml
        qml/components/PageEntrance.qml
        qml/components/PlatformPicker.qml
        qml/components/CloudLibraryActions.qml
        qml/components/PosterTile.qml
        qml/components/ReleaseNotes.qml
        qml/components/RoundedArtwork.qml
        qml/components/ScreenBackground.qml
        qml/components/SettingRow.qml
        qml/components/StoreBadge.qml
        qml/components/StreamCaptureStatus.qml
        qml/components/StreamInputNotice.qml
        qml/components/TogglePill.qml
        qml/components/TenBitWarningDialog.qml
        qml/components/VirtualKeyboard.qml
        qml/desktop/auth/DesktopSignInScreen.qml
        qml/desktop/components/DesktopBackdrop.qml
        qml/desktop/components/DesktopBrandLockup.qml
        qml/desktop/components/DesktopButton.qml
        qml/desktop/components/DesktopGameModal.qml
        qml/desktop/components/DesktopQueueSelector.qml
        qml/desktop/components/DesktopGlyph.qml
        qml/desktop/components/DesktopHeroButton.qml
        qml/desktop/components/CloudlightMascot.qml
        qml/desktop/components/HeroArtwork.qml
        qml/desktop/components/DesktopKeyHint.qml
        qml/desktop/components/DesktopPoster.qml
        qml/desktop/components/DesktopPosterOverlay.qml
        qml/desktop/components/DesktopTokens.qml
        qml/desktop/friends/DesktopFriendsScreen.qml
        qml/desktop/home/DesktopHomePoster.qml
        qml/desktop/home/DesktopHomeScreen.qml
        qml/desktop/library/DesktopLibraryScreen.qml
        qml/desktop/library/DesktopCollectionDialog.qml
        qml/desktop/settings/DesktopSettingsScreen.qml
        qml/desktop/onboarding/DesktopOnboardingScreen.qml
        qml/desktop/onboarding/DesktopOnboardingBackdrop.qml
        qml/desktop/onboarding/DesktopOnboardingModeCard.qml
        qml/desktop/onboarding/DesktopOnboardingPicture.qml
        qml/desktop/onboarding/DesktopOnboardingBoost.qml
        qml/desktop/onboarding/DesktopOnboardingNetwork.qml
        qml/desktop/settings/controls/DesktopSettingsAdvanced.qml
        qml/desktop/settings/controls/DesktopSettingsButton.qml
        qml/desktop/settings/controls/DesktopSettingsHevcHelp.qml
        qml/desktop/settings/controls/DesktopSettingsNotice.qml
        qml/desktop/settings/controls/DesktopNetworkTestDialog.qml
        qml/desktop/settings/controls/DesktopSettingsChoice.qml
        qml/desktop/settings/controls/DesktopSettingsDisclosure.qml
        qml/desktop/settings/controls/DesktopSettingsDropdown.qml
        qml/desktop/settings/controls/DesktopSettingsField.qml
        qml/desktop/settings/controls/DesktopSettingsShortcutBinding.qml
        qml/desktop/settings/controls/DesktopSettingsShortcutRow.qml
        qml/desktop/settings/controls/DesktopSettingsIcon.qml
        qml/desktop/settings/controls/DesktopSettingsPanel.qml
        qml/desktop/settings/controls/DesktopSettingsResolution.qml
        qml/desktop/settings/controls/DesktopSettingsRow.qml
        qml/desktop/settings/controls/DesktopSettingsSection.qml
        qml/desktop/settings/controls/DesktopSettingsSegmented.qml
        qml/desktop/settings/controls/DesktopSettingsSlider.qml
        qml/desktop/settings/controls/DesktopSettingsStepper.qml
        qml/desktop/settings/controls/DesktopSettingsToggle.qml
        qml/desktop/settings/pages/DesktopSettingsAboutPage.qml
        qml/desktop/settings/pages/DesktopSettingsAccountPage.qml
        qml/desktop/settings/pages/DesktopSettingsAudioPage.qml
        qml/desktop/settings/pages/DesktopSettingsConsolePage.qml
        qml/desktop/settings/pages/DesktopSettingsControllersPage.qml
        qml/desktop/settings/pages/DesktopSettingsControlsPage.qml
        qml/desktop/settings/pages/DesktopSettingsInterfacePage.qml
        qml/desktop/settings/pages/DesktopSettingsLookPage.qml
        qml/desktop/settings/pages/DesktopSettingsNetworkPage.qml
        qml/desktop/settings/pages/DesktopSettingsProfilePage.qml
        qml/desktop/settings/pages/DesktopSettingsRecordingPage.qml
        qml/desktop/settings/pages/DesktopSettingsExperimentalPage.qml
        qml/desktop/settings/pages/DesktopSettingsShortcutsPage.qml
        qml/desktop/settings/pages/DesktopSettingsStatsPage.qml
        qml/desktop/settings/pages/DesktopSettingsStoresPage.qml
        qml/desktop/settings/pages/DesktopSettingsStreamPage.qml
        qml/desktop/settings/pages/DesktopSettingsSubscriptionPage.qml
        qml/desktop/shell/DesktopApp.qml
        qml/desktop/shell/DesktopCommandPalette.qml
        qml/desktop/shell/DesktopShell.qml
        qml/desktop/shell/DesktopWindowBar.qml
        qml/desktop/store/DesktopStoreCard.qml
        qml/desktop/store/DesktopStoreChip.qml
        qml/desktop/store/DesktopStoreContent.qml
        qml/desktop/store/DesktopStoreHero.qml
        qml/desktop/store/DesktopStoreShelf.qml
        qml/desktop/stream/DesktopInStreamMenu.qml
        qml/desktop/stream/DesktopSessionStarting.qml
        qml/desktop/stream/DesktopStreamExitConfirm.qml
        qml/desktop/stream/DesktopStreamHud.qml
        qml/desktop/stream/DesktopStreamOverlayHost.qml
        qml/desktop/stream/DesktopStreamScreen.qml
        qml/desktop/stream/DesktopStreamStats.qml
        qml/desktop/stream/DesktopStreamToast.qml
        qml/desktop/stream/DesktopStreamToasts.qml
        qml/desktop/stream/overlay/OverlayCapturePage.qml
        qml/desktop/stream/overlay/OverlayCheckRow.qml
        qml/desktop/stream/overlay/OverlayChoiceMenu.qml
        qml/desktop/stream/overlay/OverlayDescribedToggle.qml
        qml/desktop/stream/overlay/OverlayDivider.qml
        qml/desktop/stream/overlay/OverlayDropdown.qml
        qml/desktop/stream/overlay/OverlayFilesPage.qml
        qml/desktop/stream/overlay/OverlayFiltersPage.qml
        qml/desktop/stream/overlay/OverlayFocusable.qml
        qml/desktop/stream/overlay/OverlayGalleryPage.qml
        qml/desktop/stream/overlay/OverlayGameplayPage.qml
        qml/desktop/stream/overlay/OverlayGeneralPage.qml
        qml/desktop/stream/overlay/OverlayHeader.qml
        qml/desktop/stream/overlay/OverlayHudPage.qml
        qml/desktop/stream/overlay/OverlayIcon.qml
        qml/desktop/stream/overlay/OverlayKeyField.qml
        qml/desktop/stream/overlay/OverlayMainPage.qml
        qml/desktop/stream/overlay/OverlayNotificationsPage.qml
        qml/desktop/stream/overlay/OverlayPage.qml
        qml/desktop/stream/overlay/OverlayRow.qml
        qml/desktop/stream/overlay/OverlaySectionLabel.qml
        qml/desktop/stream/overlay/OverlaySettingsPage.qml
        qml/desktop/stream/overlay/OverlayShortcutsPage.qml
        qml/desktop/stream/overlay/OverlaySlider.qml
        qml/desktop/stream/overlay/OverlayStepper.qml
        qml/desktop/stream/overlay/OverlayStyle.qml
        qml/desktop/stream/overlay/OverlaySystemPage.qml
        qml/desktop/stream/overlay/OverlayToggle.qml
        qml/desktop/updates/DesktopUpdateScreen.qml
        qml/overlays/FriendsOverlay.qml
        qml/overlays/GuideOverlay.qml
        qml/overlays/OverlayHost.qml
        qml/overlays/QueueAdOverlay.qml
        qml/overlays/QuickSettingsOverlay.qml
        qml/overlays/SessionConflictOverlay.qml
        qml/overlays/SessionReportOverlay.qml
        qml/screens/AccountsScreen.qml
        qml/screens/DiagnosticsScreen.qml
        qml/screens/GameAccountsScreen.qml
        qml/screens/GameDetailScreen.qml
        qml/screens/HomeScreen.qml
        qml/screens/InsertingScreen.qml
        qml/screens/JoiningScreen.qml
        qml/screens/LibraryScreen.qml
        qml/screens/MediaScreen.qml
        qml/screens/PersistentStorageScreen.qml
        qml/screens/ProfilePinScreen.qml
        qml/screens/SettingsScreen.qml
        qml/screens/SignInScreen.qml
        qml/screens/StoreScreen.qml
        qml/screens/StreamScreen.qml
        qml/screens/ThemeStoreScreen.qml
        qml/screens/UpdateScreen.qml
        qml/state/ShellStore.qml
        qml/state/SessionSetupProgress.qml
        qml/state/account/AccountServicesState.qml
        qml/state/account/QueueSelectorState.qml
        qml/state/catalog/ArtworkState.qml
        qml/state/catalog/CatalogState.qml
        qml/state/settings/SettingsState.qml
        qml/state/BackgroundStreamState.qml
        qml/state/ConnectionHealthState.qml
        qml/state/settings/OnboardingState.qml
        qml/theme/Theme.qml
    RESOURCES
        ${OPENNOW_CONTROLLER_ICON_FILES}
        ${OPENNOW_KEYBOARD_ICON_FILES}
        res/icons/nav-home.svg
        res/icons/stats-globe.svg
        res/icons/nav-library.svg
        res/icons/nav-controller.svg
        res/icons/nav-friends.svg
        res/icons/nav-settings.svg
        res/icons/nav-computer.svg
        res/icons/settings-account.svg
        res/icons/settings-streaming.svg
        res/icons/settings-video.svg
        res/icons/settings-input.svg
        res/icons/settings-network.svg
        res/icons/settings-themes.svg
        res/icons/settings-advanced.svg
        res/icons/store-steam.svg
        res/icons/store-xbox.svg
        res/icons/store-gog.svg
        res/icons/store-gaijin.svg
        res/icons/store-ea.svg
        res/icons/store-nvidia.svg
        res/icons/store-nvidia.svg
        res/icons/store-epic.svg
        res/icons/store-ubisoft.svg
        res/icons/store-battlenet.svg
        res/brand/opennow-mark.png
        res/brand/cloudlight-mark-light.png
        res/brand/signin-hero.jpg
        res/brand/desktop-renew.jpg
        res/onboarding/desktop-preview.png
        res/onboarding/console-preview.png
        res/fonts/Nunito-Variable.ttf
        res/fonts/Inter-Regular.ttf
        res/fonts/Inter-Medium.ttf
        res/fonts/Inter-SemiBold.ttf
        res/fonts/Inter-Bold.ttf
        res/fonts/InterDisplay-Medium.ttf
        res/fonts/InterDisplay-SemiBold.ttf
        res/fonts/InterDisplay-Bold.ttf
        res/fonts/CormorantGaramond-Variable.ttf
        res/fonts/IBMPlexMono-Regular.ttf
        res/fonts/IBMPlexMono-Medium.ttf
        res/fonts/IBMPlexMono-Bold.ttf
        res/icons/desktop-nav-home.svg
        res/icons/desktop-nav-home-active.svg
        res/icons/desktop-nav-library.svg
        res/icons/desktop-nav-library-active.svg
        res/icons/desktop-nav-store.svg
        res/icons/desktop-nav-store-active.svg
        res/icons/desktop-nav-friends.svg
        res/icons/desktop-nav-friends-active.svg
        res/icons/desktop-nav-settings.svg
        res/icons/desktop-nav-settings-active.svg
        res/icons/desktop-collapse.svg
        res/icons/desktop-expand.svg
        res/icons/desktop-plus.svg
        res/icons/desktop-star.svg
        res/icons/desktop-clock.svg
        res/icons/desktop-coop.svg
        res/icons/desktop-rtx.svg
        res/icons/desktop-gamepad.svg
        res/icons/desktop-chevron-up.svg
        res/icons/desktop-chevron-down.svg
        res/icons/desktop-search.svg
        res/icons/desktop-nav-home-on-light.svg
        res/icons/desktop-nav-home-active-on-light.svg
        res/icons/desktop-expand-on-light.svg
        res/icons/desktop-star-on-light.svg
        res/icons/desktop-gamepad-on-light.svg
        res/icons/desktop-chevron-up-on-light.svg
        res/icons/desktop-rtx-on-light.svg
        res/icons/desktop-search-on-light.svg
        res/icons/desktop-nav-store-on-light.svg
        res/icons/desktop-nav-store-active-on-light.svg
        res/icons/desktop-collapse-on-light.svg
        res/icons/desktop-nav-settings-on-light.svg
        res/icons/desktop-nav-settings-active-on-light.svg
        res/icons/desktop-plus-on-light.svg
        res/icons/desktop-nav-library-on-light.svg
        res/icons/desktop-nav-library-active-on-light.svg
        res/icons/desktop-coop-on-light.svg
        res/icons/desktop-nav-friends-on-light.svg
        res/icons/desktop-nav-friends-active-on-light.svg
        res/icons/desktop-clock-on-light.svg
        res/icons/desktop-play.svg
        res/icons/desktop-play-filled.svg
        res/icons/desktop-lock.svg
        res/icons/desktop-check.svg
        res/icons/desktop-shield.svg
        res/icons/desktop-qr.svg
        res/icons/desktop-info.svg
        res/icons/desktop-close.svg
        res/icons/desktop-folder.svg
        res/icons/desktop-check-mint.svg
        res/icons/desktop-check-light.svg
        res/icons/desktop-check-focus.svg
        res/icons/desktop-message.svg
        res/icons/desktop-sliders.svg
        res/icons/desktop-sliders-on-light.svg
        res/icons/desktop-user-plus.svg
        res/icons/desktop-user-plus-on-light.svg
        res/icons/desktop-logout.svg
        res/icons/desktop-logout-on-light.svg
        res/icons/desktop-plus-ink.svg
        res/icons/desktop-mic.svg
        res/icons/desktop-mic-off.svg
        res/icons/desktop-play-stroke.svg
        res/icons/desktop-play-stroke-on-light.svg
)
